[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "colectica-mcp-server"
version = "0.1.5"
description = "MCP server for Colectica Repository REST API"
readme = "README.md"
license = "Apache-2.0"
authors = [
    {name = "AYOUB KEBAILI", email = "keayoub@msn.com"}
]
maintainers = [
    {name = "AYOUB KEBAILI", email = "keayoub@msn.com"}
]
requires-python = ">=3.10"
dependencies = [
    "httpx>=0.28.0",
    "mcp>=1.16.0",
    "python-dotenv>=1.1.0",
]

[project.scripts]
colectica-mcp = "colectica_mcp.server:main"

[tool.hatch.build.targets.wheel]
packages = ["src/colectica_mcp"]
