<#
.SYNOPSIS
  Release helper for colectica-mcp-server.

.DESCRIPTION
  - Bumps `project.version` in `pyproject.toml`
  - Updates README version mentions when present
  - Creates `releases/v<version>.md` if missing
  - Commits, tags, and optionally pushes
  - Optionally validates build with `python -m build`

.USAGE
  .\scripts\release.ps1 -NewVersion 0.1.1
  .\scripts\release.ps1 -NewVersion 0.1.1 -Push
  .\scripts\release.ps1 -NewVersion 0.1.1 -Push -Build
#>

param(
  [Parameter(Mandatory = $true, Position = 0)][string]$NewVersion,
  [switch]$Push,
  [switch]$Build,
  [switch]$Force
)

function Write-Info([string]$m) { Write-Host "[INFO] $m" -ForegroundColor Cyan }
function Write-Warn([string]$m) { Write-Host "[WARN] $m" -ForegroundColor Yellow }
function Write-Err([string]$m) { Write-Host "[ERROR] $m" -ForegroundColor Red }

function Resolve-PreviousTag([string]$fallbackVersion) {
  $fallbackTag = "v$fallbackVersion"
  git rev-parse --verify "refs/tags/$fallbackTag" 2>$null | Out-Null
  if ($LASTEXITCODE -eq 0) { return $fallbackTag }

  $lastTag = (git tag --sort=-version:refname | Select-Object -First 1)
  if ($lastTag) { return $lastTag.Trim() }

  return $null
}

function New-ReleaseNotesFile([string]$repoRoot, [string]$newVersion, [string]$oldVersion) {
  $releasesDir = Join-Path $repoRoot "releases"
  if (-not (Test-Path $releasesDir -PathType Container)) {
    New-Item -ItemType Directory -Path $releasesDir -Force | Out-Null
  }

  $notesPath = Join-Path $releasesDir ("v{0}.md" -f $newVersion)
  if (Test-Path $notesPath -PathType Leaf) {
    Write-Info "Release notes already exist: $notesPath"
    return $notesPath
  }

  $previousTag = Resolve-PreviousTag -fallbackVersion $oldVersion
  $range = $null
  if ($previousTag) {
    $range = "$previousTag..HEAD"
    Write-Info "Generating release notes from range: $range"
  } else {
    Write-Warn "No previous tag found. Generating release notes from recent commits."
  }

  $commitLines = @()
  if ($range) {
    $commitLines = @(git log $range --pretty=format:"- %h %s")
  } else {
    $commitLines = @(git log -n 20 --pretty=format:"- %h %s")
  }
  if (-not $commitLines -or $commitLines.Count -eq 0) {
    $commitLines = @("- Initial release notes entry")
  }

  $changedFiles = @()
  if ($range) { $changedFiles = @(git diff --name-only $range) }
  if (-not $changedFiles -or $changedFiles.Count -eq 0) {
    $changedFiles = @("No file changes detected in computed range")
  }

  $today = Get-Date -Format "MMMM d, yyyy"
  $header = @(
    "# Release Notes - v$newVersion",
    "",
    "**Release Date**: $today",
    "**Previous Version**: $oldVersion",
    "",
    "---",
    "",
    "## Overview",
    "",
    "v$newVersion release generated by release automation script.",
    "",
    "---",
    "",
    "## Commits",
    ""
  )

  $filesHeader = @(
    "",
    "---",
    "",
    "## Changed Areas",
    ""
  )

  $fileLines = $changedFiles | ForEach-Object { ('- `{0}`' -f $_) }

  $contentLines = @()
  $contentLines += $header
  $contentLines += $commitLines
  $contentLines += $filesHeader
  $contentLines += $fileLines

  $content = $contentLines -join "`n"
  $Utf8NoBomEncoding = New-Object System.Text.UTF8Encoding $False
  [System.IO.File]::WriteAllText($notesPath, $content, $Utf8NoBomEncoding)
  Write-Info "Release notes generated: $notesPath"

  return $notesPath
}

if (-not ($NewVersion -match '^[0-9]+\.[0-9]+\.[0-9]+(-[A-Za-z0-9\.]+)?$')) {
  Write-Err "Version '$NewVersion' doesn't look like semantic versioning (MAJOR.MINOR.PATCH)."
  exit 2
}

try { git --version | Out-Null } catch { Write-Err "git is not available on PATH"; exit 3 }

$repoRoot = (git rev-parse --show-toplevel) 2>&1
if ($LASTEXITCODE -ne 0) { Write-Err "Not inside a git repository."; exit 4 }
$repoRoot = $repoRoot.Trim()
Set-Location $repoRoot

$status = git status --porcelain
if ($status -and -not $Force) {
  Write-Err "Working tree is not clean. Commit or stash changes first, or use -Force."
  git status --short
  exit 5
}

$pyproject = Join-Path $repoRoot "pyproject.toml"
$readme = Join-Path $repoRoot "README.md"

if (-not (Test-Path $pyproject -PathType Leaf)) {
  Write-Err "pyproject.toml not found at $pyproject"
  exit 6
}

$pytext = Get-Content -Raw -Path $pyproject
$matchInfo = Select-String -Path $pyproject -Pattern '^[ \t]*version[ \t]*=[ \t]*"([^\"]+)"' -AllMatches
if (-not $matchInfo -or $matchInfo.Count -eq 0) {
  Write-Err "Could not find current version in pyproject.toml"
  exit 7
}

$firstMatch = $matchInfo[0].Matches[0]
$oldVersion = $firstMatch.Groups[1].Value
Write-Info "Current version: $oldVersion -> New version: $NewVersion"

if ($oldVersion -eq $NewVersion) {
  Write-Warn "New version is identical to current version. Nothing to do."
  exit 0
}

$patternPy = '(version\s*=\s*")([^"]+)(")'
$newPy = [regex]::Replace(
  $pytext,
  $patternPy,
  {
    param($m)
    return $m.Groups[1].Value + $NewVersion + $m.Groups[3].Value
  },
  [System.Text.RegularExpressions.RegexOptions]::Multiline
)
$Utf8NoBomEncoding = New-Object System.Text.UTF8Encoding $False
[System.IO.File]::WriteAllText($pyproject, $newPy, $Utf8NoBomEncoding)

if (Test-Path $readme) {
  $readmeText = [System.IO.File]::ReadAllText($readme, $Utf8NoBomEncoding)
  $updatedReadme = $readmeText -replace [regex]::Escape("v$oldVersion"), "v$NewVersion"
  [System.IO.File]::WriteAllText($readme, $updatedReadme, $Utf8NoBomEncoding)
}

$releaseNotesFile = New-ReleaseNotesFile -repoRoot $repoRoot -newVersion $NewVersion -oldVersion $oldVersion

if ($Build) {
  Write-Info "Running build validation: uv build"
  uv build
  if ($LASTEXITCODE -ne 0) { Write-Err "Package build failed"; exit 14 }
}

Write-Info "Staging release artifacts..."
if (Test-Path $readme) {
  git add $pyproject $readme $releaseNotesFile
} else {
  git add $pyproject $releaseNotesFile
}
if ($LASTEXITCODE -ne 0) { Write-Err "git add failed"; exit 8 }

$commitMsg = "Bump version to $NewVersion"
Write-Info "Committing: $commitMsg"
git commit -m $commitMsg --no-verify
if ($LASTEXITCODE -ne 0) { Write-Err "git commit failed"; exit 9 }

Write-Info "Creating annotated tag v$NewVersion"
git tag -a "v$NewVersion" -m "Release v$NewVersion"
if ($LASTEXITCODE -ne 0) { Write-Err "git tag failed"; exit 10 }

if ($Push) {
  Write-Info "Pushing commit to origin..."
  git push origin HEAD
  if ($LASTEXITCODE -ne 0) { Write-Err "git push failed"; exit 11 }

  Write-Info "Pushing tag v$NewVersion to origin..."
  git push origin "v$NewVersion"
  if ($LASTEXITCODE -ne 0) { Write-Err "git push tag failed"; exit 12 }
}

Write-Info "Release steps completed successfully. New tag: v$NewVersion"
exit 0
